// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/librus_scraper.proto

package librus_scraper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED  MessageType = 0
	MessageType_MESSAGE_TYPE_MESSAGE      MessageType = 1 // Personal messages from /wiadomosci
	MessageType_MESSAGE_TYPE_NOTIFICATION MessageType = 2 // News/announcements from /ogloszenia
	MessageType_MESSAGE_TYPE_NEWS         MessageType = 3 // Reserved for future use
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_MESSAGE",
		2: "MESSAGE_TYPE_NOTIFICATION",
		3: "MESSAGE_TYPE_NEWS",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":  0,
		"MESSAGE_TYPE_MESSAGE":      1,
		"MESSAGE_TYPE_NOTIFICATION": 2,
		"MESSAGE_TYPE_NEWS":         3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_librus_scraper_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_librus_scraper_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{0}
}

// Health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_librus_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_librus_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Login validation
type ValidateLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateLoginRequest) Reset() {
	*x = ValidateLoginRequest{}
	mi := &file_proto_librus_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateLoginRequest) ProtoMessage() {}

func (x *ValidateLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateLoginRequest.ProtoReflect.Descriptor instead.
func (*ValidateLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateLoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ValidateLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ValidateLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateLoginResponse) Reset() {
	*x = ValidateLoginResponse{}
	mi := &file_proto_librus_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateLoginResponse) ProtoMessage() {}

func (x *ValidateLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateLoginResponse.ProtoReflect.Descriptor instead.
func (*ValidateLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{3}
}

// Message operations
type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`       // unique identifier and for session creation/restoration
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // for session creation/restoration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_librus_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessagesRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetMessagesRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_librus_scraper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetSingleMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MessageUrl    string                 `protobuf:"bytes,3,opt,name=message_url,json=messageUrl,proto3" json:"message_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSingleMessageRequest) Reset() {
	*x = GetSingleMessageRequest{}
	mi := &file_proto_librus_scraper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSingleMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleMessageRequest) ProtoMessage() {}

func (x *GetSingleMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleMessageRequest.ProtoReflect.Descriptor instead.
func (*GetSingleMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{6}
}

func (x *GetSingleMessageRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetSingleMessageRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetSingleMessageRequest) GetMessageUrl() string {
	if x != nil {
		return x.MessageUrl
	}
	return ""
}

type GetSingleMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSingleMessageResponse) Reset() {
	*x = GetSingleMessageResponse{}
	mi := &file_proto_librus_scraper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSingleMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleMessageResponse) ProtoMessage() {}

func (x *GetSingleMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleMessageResponse.ProtoReflect.Descriptor instead.
func (*GetSingleMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{7}
}

func (x *GetSingleMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type AnswerMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MessageUrl    string                 `protobuf:"bytes,3,opt,name=message_url,json=messageUrl,proto3" json:"message_url,omitempty"`
	AnswerText    string                 `protobuf:"bytes,4,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerMessageRequest) Reset() {
	*x = AnswerMessageRequest{}
	mi := &file_proto_librus_scraper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerMessageRequest) ProtoMessage() {}

func (x *AnswerMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerMessageRequest.ProtoReflect.Descriptor instead.
func (*AnswerMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{8}
}

func (x *AnswerMessageRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AnswerMessageRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AnswerMessageRequest) GetMessageUrl() string {
	if x != nil {
		return x.MessageUrl
	}
	return ""
}

func (x *AnswerMessageRequest) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

type AnswerMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerMessageResponse) Reset() {
	*x = AnswerMessageResponse{}
	mi := &file_proto_librus_scraper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerMessageResponse) ProtoMessage() {}

func (x *AnswerMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerMessageResponse.ProtoReflect.Descriptor instead.
func (*AnswerMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{9}
}

// News operations
type GetNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsRequest) Reset() {
	*x = GetNewsRequest{}
	mi := &file_proto_librus_scraper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsRequest) ProtoMessage() {}

func (x *GetNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsRequest.ProtoReflect.Descriptor instead.
func (*GetNewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{10}
}

func (x *GetNewsRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetNewsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*Message             `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsResponse) Reset() {
	*x = GetNewsResponse{}
	mi := &file_proto_librus_scraper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsResponse) ProtoMessage() {}

func (x *GetNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsResponse.ProtoReflect.Descriptor instead.
func (*GetNewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{11}
}

func (x *GetNewsResponse) GetNews() []*Message {
	if x != nil {
		return x.News
	}
	return nil
}

// Combined operations
type GetAllUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUpdatesRequest) Reset() {
	*x = GetAllUpdatesRequest{}
	mi := &file_proto_librus_scraper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUpdatesRequest) ProtoMessage() {}

func (x *GetAllUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUpdatesRequest.ProtoReflect.Descriptor instead.
func (*GetAllUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllUpdatesRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetAllUpdatesRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetAllUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // Personal messages
	News          []*Message             `protobuf:"bytes,2,rep,name=news,proto3" json:"news,omitempty"`         // News/announcements
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUpdatesResponse) Reset() {
	*x = GetAllUpdatesResponse{}
	mi := &file_proto_librus_scraper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUpdatesResponse) ProtoMessage() {}

func (x *GetAllUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUpdatesResponse.ProtoReflect.Descriptor instead.
func (*GetAllUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllUpdatesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetAllUpdatesResponse) GetNews() []*Message {
	if x != nil {
		return x.News
	}
	return nil
}

// Data models
type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=librus_scraper.MessageType" json:"type,omitempty"`
	Link           string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Author         string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	DateTimestamp  int64                  `protobuf:"varint,7,opt,name=date_timestamp,json=dateTimestamp,proto3" json:"date_timestamp,omitempty"`   // Unix timestamp
	AttachmentsDir string                 `protobuf:"bytes,8,opt,name=attachments_dir,json=attachmentsDir,proto3" json:"attachments_dir,omitempty"` // Path to directory with attachments (like in Go model)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_librus_scraper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_librus_scraper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_librus_scraper_proto_rawDescGZIP(), []int{14}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Message) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Message) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetDateTimestamp() int64 {
	if x != nil {
		return x.DateTimestamp
	}
	return 0
}

func (x *Message) GetAttachmentsDir() string {
	if x != nil {
		return x.AttachmentsDir
	}
	return ""
}

var File_proto_librus_scraper_proto protoreflect.FileDescriptor

const file_proto_librus_scraper_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/librus_scraper.proto\x12\x0elibrus_scraper\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"H\n" +
	"\x14ValidateLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x17\n" +
	"\x15ValidateLoginResponse\"F\n" +
	"\x12GetMessagesRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"J\n" +
	"\x13GetMessagesResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.librus_scraper.MessageR\bmessages\"l\n" +
	"\x17GetSingleMessageRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vmessage_url\x18\x03 \x01(\tR\n" +
	"messageUrl\"M\n" +
	"\x18GetSingleMessageResponse\x121\n" +
	"\amessage\x18\x01 \x01(\v2\x17.librus_scraper.MessageR\amessage\"\x8a\x01\n" +
	"\x14AnswerMessageRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vmessage_url\x18\x03 \x01(\tR\n" +
	"messageUrl\x12\x1f\n" +
	"\vanswer_text\x18\x04 \x01(\tR\n" +
	"answerText\"\x17\n" +
	"\x15AnswerMessageResponse\"B\n" +
	"\x0eGetNewsRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\x0fGetNewsResponse\x12+\n" +
	"\x04news\x18\x01 \x03(\v2\x17.librus_scraper.MessageR\x04news\"H\n" +
	"\x14GetAllUpdatesRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"y\n" +
	"\x15GetAllUpdatesResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.librus_scraper.MessageR\bmessages\x12+\n" +
	"\x04news\x18\x02 \x03(\v2\x17.librus_scraper.MessageR\x04news\"\xf6\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.librus_scraper.MessageTypeR\x04type\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12%\n" +
	"\x0edate_timestamp\x18\a \x01(\x03R\rdateTimestamp\x12'\n" +
	"\x0fattachments_dir\x18\b \x01(\tR\x0eattachmentsDir*{\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MESSAGE_TYPE_MESSAGE\x10\x01\x12\x1d\n" +
	"\x19MESSAGE_TYPE_NOTIFICATION\x10\x02\x12\x15\n" +
	"\x11MESSAGE_TYPE_NEWS\x10\x032\x8c\x05\n" +
	"\rLibrusScraper\x12V\n" +
	"\vGetMessages\x12\".librus_scraper.GetMessagesRequest\x1a#.librus_scraper.GetMessagesResponse\x12e\n" +
	"\x10GetSingleMessage\x12'.librus_scraper.GetSingleMessageRequest\x1a(.librus_scraper.GetSingleMessageResponse\x12\\\n" +
	"\rAnswerMessage\x12$.librus_scraper.AnswerMessageRequest\x1a%.librus_scraper.AnswerMessageResponse\x12J\n" +
	"\aGetNews\x12\x1e.librus_scraper.GetNewsRequest\x1a\x1f.librus_scraper.GetNewsResponse\x12\\\n" +
	"\rGetAllUpdates\x12$.librus_scraper.GetAllUpdatesRequest\x1a%.librus_scraper.GetAllUpdatesResponse\x12V\n" +
	"\vHealthCheck\x12\".librus_scraper.HealthCheckRequest\x1a#.librus_scraper.HealthCheckResponse\x12\\\n" +
	"\rValidateLogin\x12$.librus_scraper.ValidateLoginRequest\x1a%.librus_scraper.ValidateLoginResponseB\x1dZ\x1blibrus/proto/librus_scraperb\x06proto3"

var (
	file_proto_librus_scraper_proto_rawDescOnce sync.Once
	file_proto_librus_scraper_proto_rawDescData []byte
)

func file_proto_librus_scraper_proto_rawDescGZIP() []byte {
	file_proto_librus_scraper_proto_rawDescOnce.Do(func() {
		file_proto_librus_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_librus_scraper_proto_rawDesc), len(file_proto_librus_scraper_proto_rawDesc)))
	})
	return file_proto_librus_scraper_proto_rawDescData
}

var file_proto_librus_scraper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_librus_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_librus_scraper_proto_goTypes = []any{
	(MessageType)(0),                 // 0: librus_scraper.MessageType
	(*HealthCheckRequest)(nil),       // 1: librus_scraper.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 2: librus_scraper.HealthCheckResponse
	(*ValidateLoginRequest)(nil),     // 3: librus_scraper.ValidateLoginRequest
	(*ValidateLoginResponse)(nil),    // 4: librus_scraper.ValidateLoginResponse
	(*GetMessagesRequest)(nil),       // 5: librus_scraper.GetMessagesRequest
	(*GetMessagesResponse)(nil),      // 6: librus_scraper.GetMessagesResponse
	(*GetSingleMessageRequest)(nil),  // 7: librus_scraper.GetSingleMessageRequest
	(*GetSingleMessageResponse)(nil), // 8: librus_scraper.GetSingleMessageResponse
	(*AnswerMessageRequest)(nil),     // 9: librus_scraper.AnswerMessageRequest
	(*AnswerMessageResponse)(nil),    // 10: librus_scraper.AnswerMessageResponse
	(*GetNewsRequest)(nil),           // 11: librus_scraper.GetNewsRequest
	(*GetNewsResponse)(nil),          // 12: librus_scraper.GetNewsResponse
	(*GetAllUpdatesRequest)(nil),     // 13: librus_scraper.GetAllUpdatesRequest
	(*GetAllUpdatesResponse)(nil),    // 14: librus_scraper.GetAllUpdatesResponse
	(*Message)(nil),                  // 15: librus_scraper.Message
}
var file_proto_librus_scraper_proto_depIdxs = []int32{
	15, // 0: librus_scraper.GetMessagesResponse.messages:type_name -> librus_scraper.Message
	15, // 1: librus_scraper.GetSingleMessageResponse.message:type_name -> librus_scraper.Message
	15, // 2: librus_scraper.GetNewsResponse.news:type_name -> librus_scraper.Message
	15, // 3: librus_scraper.GetAllUpdatesResponse.messages:type_name -> librus_scraper.Message
	15, // 4: librus_scraper.GetAllUpdatesResponse.news:type_name -> librus_scraper.Message
	0,  // 5: librus_scraper.Message.type:type_name -> librus_scraper.MessageType
	5,  // 6: librus_scraper.LibrusScraper.GetMessages:input_type -> librus_scraper.GetMessagesRequest
	7,  // 7: librus_scraper.LibrusScraper.GetSingleMessage:input_type -> librus_scraper.GetSingleMessageRequest
	9,  // 8: librus_scraper.LibrusScraper.AnswerMessage:input_type -> librus_scraper.AnswerMessageRequest
	11, // 9: librus_scraper.LibrusScraper.GetNews:input_type -> librus_scraper.GetNewsRequest
	13, // 10: librus_scraper.LibrusScraper.GetAllUpdates:input_type -> librus_scraper.GetAllUpdatesRequest
	1,  // 11: librus_scraper.LibrusScraper.HealthCheck:input_type -> librus_scraper.HealthCheckRequest
	3,  // 12: librus_scraper.LibrusScraper.ValidateLogin:input_type -> librus_scraper.ValidateLoginRequest
	6,  // 13: librus_scraper.LibrusScraper.GetMessages:output_type -> librus_scraper.GetMessagesResponse
	8,  // 14: librus_scraper.LibrusScraper.GetSingleMessage:output_type -> librus_scraper.GetSingleMessageResponse
	10, // 15: librus_scraper.LibrusScraper.AnswerMessage:output_type -> librus_scraper.AnswerMessageResponse
	12, // 16: librus_scraper.LibrusScraper.GetNews:output_type -> librus_scraper.GetNewsResponse
	14, // 17: librus_scraper.LibrusScraper.GetAllUpdates:output_type -> librus_scraper.GetAllUpdatesResponse
	2,  // 18: librus_scraper.LibrusScraper.HealthCheck:output_type -> librus_scraper.HealthCheckResponse
	4,  // 19: librus_scraper.LibrusScraper.ValidateLogin:output_type -> librus_scraper.ValidateLoginResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_librus_scraper_proto_init() }
func file_proto_librus_scraper_proto_init() {
	if File_proto_librus_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_librus_scraper_proto_rawDesc), len(file_proto_librus_scraper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_librus_scraper_proto_goTypes,
		DependencyIndexes: file_proto_librus_scraper_proto_depIdxs,
		EnumInfos:         file_proto_librus_scraper_proto_enumTypes,
		MessageInfos:      file_proto_librus_scraper_proto_msgTypes,
	}.Build()
	File_proto_librus_scraper_proto = out.File
	file_proto_librus_scraper_proto_goTypes = nil
	file_proto_librus_scraper_proto_depIdxs = nil
}
