// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/librus_scraper.proto

package librus_scraper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LibrusScraper_GetMessages_FullMethodName      = "/librus_scraper.LibrusScraper/GetMessages"
	LibrusScraper_GetSingleMessage_FullMethodName = "/librus_scraper.LibrusScraper/GetSingleMessage"
	LibrusScraper_AnswerMessage_FullMethodName    = "/librus_scraper.LibrusScraper/AnswerMessage"
	LibrusScraper_GetNews_FullMethodName          = "/librus_scraper.LibrusScraper/GetNews"
	LibrusScraper_GetAllUpdates_FullMethodName    = "/librus_scraper.LibrusScraper/GetAllUpdates"
	LibrusScraper_HealthCheck_FullMethodName      = "/librus_scraper.LibrusScraper/HealthCheck"
	LibrusScraper_ValidateLogin_FullMethodName    = "/librus_scraper.LibrusScraper/ValidateLogin"
)

// LibrusScraperClient is the client API for LibrusScraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Main scraper service
type LibrusScraperClient interface {
	// Message operations (authentication handled internally)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	GetSingleMessage(ctx context.Context, in *GetSingleMessageRequest, opts ...grpc.CallOption) (*GetSingleMessageResponse, error)
	AnswerMessage(ctx context.Context, in *AnswerMessageRequest, opts ...grpc.CallOption) (*AnswerMessageResponse, error)
	// News/announcements operations
	GetNews(ctx context.Context, in *GetNewsRequest, opts ...grpc.CallOption) (*GetNewsResponse, error)
	// Combined operations (messages + news in one call)
	GetAllUpdates(ctx context.Context, in *GetAllUpdatesRequest, opts ...grpc.CallOption) (*GetAllUpdatesResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Login validation - performs login and validates session
	ValidateLogin(ctx context.Context, in *ValidateLoginRequest, opts ...grpc.CallOption) (*ValidateLoginResponse, error)
}

type librusScraperClient struct {
	cc grpc.ClientConnInterface
}

func NewLibrusScraperClient(cc grpc.ClientConnInterface) LibrusScraperClient {
	return &librusScraperClient{cc}
}

func (c *librusScraperClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, LibrusScraper_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *librusScraperClient) GetSingleMessage(ctx context.Context, in *GetSingleMessageRequest, opts ...grpc.CallOption) (*GetSingleMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSingleMessageResponse)
	err := c.cc.Invoke(ctx, LibrusScraper_GetSingleMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *librusScraperClient) AnswerMessage(ctx context.Context, in *AnswerMessageRequest, opts ...grpc.CallOption) (*AnswerMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerMessageResponse)
	err := c.cc.Invoke(ctx, LibrusScraper_AnswerMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *librusScraperClient) GetNews(ctx context.Context, in *GetNewsRequest, opts ...grpc.CallOption) (*GetNewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewsResponse)
	err := c.cc.Invoke(ctx, LibrusScraper_GetNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *librusScraperClient) GetAllUpdates(ctx context.Context, in *GetAllUpdatesRequest, opts ...grpc.CallOption) (*GetAllUpdatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUpdatesResponse)
	err := c.cc.Invoke(ctx, LibrusScraper_GetAllUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *librusScraperClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, LibrusScraper_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *librusScraperClient) ValidateLogin(ctx context.Context, in *ValidateLoginRequest, opts ...grpc.CallOption) (*ValidateLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateLoginResponse)
	err := c.cc.Invoke(ctx, LibrusScraper_ValidateLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibrusScraperServer is the server API for LibrusScraper service.
// All implementations must embed UnimplementedLibrusScraperServer
// for forward compatibility.
//
// Main scraper service
type LibrusScraperServer interface {
	// Message operations (authentication handled internally)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	GetSingleMessage(context.Context, *GetSingleMessageRequest) (*GetSingleMessageResponse, error)
	AnswerMessage(context.Context, *AnswerMessageRequest) (*AnswerMessageResponse, error)
	// News/announcements operations
	GetNews(context.Context, *GetNewsRequest) (*GetNewsResponse, error)
	// Combined operations (messages + news in one call)
	GetAllUpdates(context.Context, *GetAllUpdatesRequest) (*GetAllUpdatesResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Login validation - performs login and validates session
	ValidateLogin(context.Context, *ValidateLoginRequest) (*ValidateLoginResponse, error)
	mustEmbedUnimplementedLibrusScraperServer()
}

// UnimplementedLibrusScraperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLibrusScraperServer struct{}

func (UnimplementedLibrusScraperServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedLibrusScraperServer) GetSingleMessage(context.Context, *GetSingleMessageRequest) (*GetSingleMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingleMessage not implemented")
}
func (UnimplementedLibrusScraperServer) AnswerMessage(context.Context, *AnswerMessageRequest) (*AnswerMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerMessage not implemented")
}
func (UnimplementedLibrusScraperServer) GetNews(context.Context, *GetNewsRequest) (*GetNewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNews not implemented")
}
func (UnimplementedLibrusScraperServer) GetAllUpdates(context.Context, *GetAllUpdatesRequest) (*GetAllUpdatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUpdates not implemented")
}
func (UnimplementedLibrusScraperServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedLibrusScraperServer) ValidateLogin(context.Context, *ValidateLoginRequest) (*ValidateLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateLogin not implemented")
}
func (UnimplementedLibrusScraperServer) mustEmbedUnimplementedLibrusScraperServer() {}
func (UnimplementedLibrusScraperServer) testEmbeddedByValue()                       {}

// UnsafeLibrusScraperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LibrusScraperServer will
// result in compilation errors.
type UnsafeLibrusScraperServer interface {
	mustEmbedUnimplementedLibrusScraperServer()
}

func RegisterLibrusScraperServer(s grpc.ServiceRegistrar, srv LibrusScraperServer) {
	// If the following call pancis, it indicates UnimplementedLibrusScraperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LibrusScraper_ServiceDesc, srv)
}

func _LibrusScraper_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibrusScraperServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibrusScraper_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibrusScraperServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibrusScraper_GetSingleMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSingleMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibrusScraperServer).GetSingleMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibrusScraper_GetSingleMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibrusScraperServer).GetSingleMessage(ctx, req.(*GetSingleMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibrusScraper_AnswerMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibrusScraperServer).AnswerMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibrusScraper_AnswerMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibrusScraperServer).AnswerMessage(ctx, req.(*AnswerMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibrusScraper_GetNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibrusScraperServer).GetNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibrusScraper_GetNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibrusScraperServer).GetNews(ctx, req.(*GetNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibrusScraper_GetAllUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUpdatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibrusScraperServer).GetAllUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibrusScraper_GetAllUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibrusScraperServer).GetAllUpdates(ctx, req.(*GetAllUpdatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibrusScraper_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibrusScraperServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibrusScraper_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibrusScraperServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibrusScraper_ValidateLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibrusScraperServer).ValidateLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LibrusScraper_ValidateLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibrusScraperServer).ValidateLogin(ctx, req.(*ValidateLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LibrusScraper_ServiceDesc is the grpc.ServiceDesc for LibrusScraper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LibrusScraper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "librus_scraper.LibrusScraper",
	HandlerType: (*LibrusScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessages",
			Handler:    _LibrusScraper_GetMessages_Handler,
		},
		{
			MethodName: "GetSingleMessage",
			Handler:    _LibrusScraper_GetSingleMessage_Handler,
		},
		{
			MethodName: "AnswerMessage",
			Handler:    _LibrusScraper_AnswerMessage_Handler,
		},
		{
			MethodName: "GetNews",
			Handler:    _LibrusScraper_GetNews_Handler,
		},
		{
			MethodName: "GetAllUpdates",
			Handler:    _LibrusScraper_GetAllUpdates_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _LibrusScraper_HealthCheck_Handler,
		},
		{
			MethodName: "ValidateLogin",
			Handler:    _LibrusScraper_ValidateLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/librus_scraper.proto",
}
